pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-server-ip')
    }

    stages {
        stage('Setup') {
            steps {
                dir('02-single-server-deployment') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('02-single-server-deployment') {
                    sh 'python3 -m pytest'
                }
            }
        }

        stage('Package code') {
            steps {
                dir('02-single-server-deployment') {
                    sh "zip -r myapp.zip ./* -x '*.git*'"
                    sh 'ls -lart'
                }
            }
        }

        stage('Deploy to Prod') {
            steps {
                dir('02-single-server-deployment') {
                    withCredentials([
                        sshUserPrivateKey(
                            credentialsId: 'ssh-key',
                            keyFileVariable: 'MY_SSH_KEY',
                            usernameVariable: 'username'
                        )
                    ]) {
                        sh '''
                            scp -i "$MY_SSH_KEY" \
                                -o StrictHostKeyChecking=no \
                                myapp.zip \
                                "${username}@${SERVER_IP}:/home/ec2-user/"

                            ssh -i "$MY_SSH_KEY" \
                                -o StrictHostKeyChecking=no \
                                "${username}@${SERVER_IP}" << EOF

                                unzip -o /home/ec2-user/myapp.zip \
                                    -d /home/ec2-user/app/

                                cd /home/ec2-user/app/

                                python3 -m venv venv

                                source /home/ec2-user/app/venv/bin/activate
                                

                                python3 -m pip install --upgrade pip
                                python3 -m pip install -r requirements.txt

                                sudo cp /home/ec2-user/app/flask.service /etc/systemd/system/flaskapp.service

                                sudo systemctl daemon-reload
                                sudo systemctl enable flaskapp.service
                                sudo systemctl restart flaskapp.service
EOF
                        '''
                    }
                }
            }
        }
    }
}