pipeline {
    agent any

    environment {
        IMAGE_NAME = 'gopikrishnachodapaneedi/jenkins-lab'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        
    }

    
    stages {

        stage('Setup') {
            steps {
                sh "pip install -r 04-docker/requirements.txt"
            }
        }
        stage('Test') {
            steps {
                dir('04-docker') {
                    sh "pytest"
                }
            }
        }

        stage('Login to docker hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'DOCKER_TOKEN')]) {
                sh 'echo ${DOCKER_TOKEN} | docker login -u ${USERNAME} --password-stdin'}
                echo 'Login successfully'
            }
        }

        stage('Build Docker Image')
        {
            steps{
                dir('04-docker'){ 
                sh 'docker build -t ${IMAGE_TAG} .'
                echo "Docker image build successfully"
                sh 'docker image ls'
                }
            }
        }

        stage('Push Docker Image')
        {
            steps
            {
                sh 'docker push ${IMAGE_TAG}'
                echo "Docker image push successfully"
            }
        }      
    }
}